[
    {
        _id: "ST_1",
        surname: "Damith",
        firstname: "Anuradha",
        lastname: "Amarasena",
        username: "@_Damith",
        password: "$2a$12$uSJ54j06KEDFbQ1QIouOzOx.nqeTi3dJ/iTeA9byBN.zKkym74n9W",
        email: "damith@gamil.com",
        age: 23,
        startyear: 2000,
        imagepath: "imageST_1.jpg",
        birthdate: "2020-10-21 00:00:00",
        gender: "male",
        addressline1: "5D 53",
        addressline2: "Natianal housing scheme",
        addressline3: "raddolugama",
        city: "seeduwa",
        mobile: "0771346601",
    },
];
