[
    {
        "teacherid": "AC_1",
        "surname": "Ruwan",
        "firstname": "Ranaweera",
        "lastname": "De silve",
        "username": "@_Ranweer",
        "password": "$2a$12$uSJ54j06KEDFbQ1QIouOzOx.nqeTi3dJ/iTeA9byBN.zKkym74n9W",
        "email": "ranweer@gamil.com",
        "age": 43,
        "startyear": 1999,
        "imagepath": "image/ST_1.jpg",
        "role": "teacher",
        "grades": 'Grade A ',
        "subjects": "mathematices",
        "birthdate": "2020-10-21 00:00:00",
        "gender": "male",
        "addressline1": "5D 53",
        "description": "I am the best mathematics teacher",
        "addressline2": "Natianal housing scheme",
        "addressline3": "raddolugama",
        "city": "seeduwa",
        "mobile": "0771346601",
    },
];
